Repository louissullivan4/diana, pull requests merged in 2025-04, with the labels that each got.

#13 Adds missing data notification
  backend/src/config/trackedSummoners.js
  src/discord/discordService.js
  src/discord/matchMonitoringService.js
  src/services/dataDragonService.js
  src/services/riotService.js
  src/services/summonerService.js
  src/services/updateMissingDataService.js
Labels: enhancement

#16 Added linting and new build workflow
  .github/workflows/ci.yml
  .gitignore
  eslint.config.mjs
  package-lock.json
  package.json
  src/app.js
  src/config/trackedSummoners.js
  src/controllers/matchController.js
  src/controllers/summonerController.js
  src/discord/bot.js
  src/discord/discordService.js
  src/discord/gameTracker.js
  src/discord/matchMonitoringService.js
  src/models/db.js
  src/routes/matchRoutes.js
  src/routes/summonerRoutes.js
  src/services/dataDragonService.js
  src/services/matchService.js
  src/services/rankService.js
  src/services/riotService.js
  src/services/summonerService.js
  src/services/updateMissingDataService.js
  test/discordService.test.js
Labels: feature

#21 feat: update project to typescript
  .github/workflows/ci.yml
  .husky/pre-commit
  .prettierignore
  .prettierrc.json
  eslint.config.mjs
  package-lock.json
  package.json
  src/app.js
  src/app.ts
  src/config/trackedSummoners.js
  src/config/trackedSummoners.ts
  src/controllers/matchController.js
  src/controllers/matchController.ts
  src/controllers/summonerController.js
  src/controllers/summonerController.ts
  src/discord/bot.js
  src/discord/bot.ts
  src/discord/discordService.js
  src/discord/discordService.ts
  src/discord/gameTracker.js
  src/discord/gameTracker.ts
  src/discord/matchMonitoringService.js
  src/discord/matchMonitoringService.ts
  src/models/db.js
  src/models/db.ts
  src/routes/matchRoutes.js
  src/routes/matchRoutes.ts
  src/routes/summonerRoutes.js
  src/routes/summonerRoutes.ts
  src/services/dataDragonService.js
  src/services/dataDragonService.ts
  src/services/matchService.js
  src/services/matchService.ts
  src/services/rankService.js
  src/services/rankService.ts
  src/services/riotService.js
  src/services/riotService.ts
  src/services/summonerService.js
  src/services/summonerService.ts
  src/services/updateMissingDataService.js
  src/services/updateMissingDataService.ts
  src/types.ts
  test/discordService.test.js
  tsconfig.json
Labels: chore, backend, bot

#23 Refactored directories
  .gitignore
  package-lock.json
  package.json
  src/api/app.ts
  src/api/matches/matchController.ts
  src/api/matches/matchRoutes.ts
  src/api/matches/matchService.ts
  src/api/summoners/summonerController.ts
  src/api/summoners/summonerRoutes.ts
  src/api/summoners/summonerService.ts
  src/api/utils/dataDragonService.ts
  src/api/utils/db.ts
  src/api/utils/rankService.ts
  src/api/utils/riotService.ts
  src/discord/gameTracker.ts
  src/discord/matchMonitoringService.ts
  src/discord/updateMissingDataService.ts
Labels: chore

#24 Fix build script and dockerfile
  Dockerfile
  Dockerfile.web
  package.json
Labels: bug
